version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "blastcms_postgres"
    environment:
        POSTGRES_USER: blastcms_user
        POSTGRES_PASSWORD: not_magical_scary
        POSTGRES_DB: blastcms_database
    ports:
      - "5432:5432"
    volumes:
      - blastcms_dbdata:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
    blastcms_dbdata:
